### ISSUE TITLE
support DATABASE_URL env

### ISSUE THREAD

**Issue by winebarrel** [winebarrel/ridgepole#123]

**Comment by sakuro** [comment]
Does this issue mean to make database config fall back to the _environment variable_ `DATABASE_URL` when `-c` is missing?

**Comment by winebarrel** [comment]
> Does this issue mean to make database config fall back to the environment variable DATABASE_URL when -c is missing?

yes

**Comment by winebarrel** [comment]
>  Does this issue mean to make database config fall back to the environment variable DATABASE_URL when -c is missing?

I'm sorry. Implementation changed.
When `-c env:HOG` is passed, ridgepole get the config from `ENV['HOGE']`.
