### ISSUE TITLE
[bug report] Execute a needless drop_table query 

### ISSUE THREAD

**Issue by sachin21** [winebarrel/ridgepole#125]
# Report
Hi there. Thank you for creating helpful gem!
When I'm renaming the table, I encountered a problem.  Could you lend me a hand?

## Summary
When I renaming the table to `arts` to `art_categories` and apply it, It will be executing renmae_table and drop_table.
It executed rename_table before drop_table so its database does not exist because renamed that table.
Why does it execute drop_table?

## Environment information
- ridgepole: v0.6.4
- DB: MySQL and mysql2 adapter
- Ruby: 2.3.3

### 1
Write this table
```
create_table :arts, force: :cascade do |t|
# *-* columns *-*
end
```

### 2
Execute following.
```
bundle exec ridgepole -E test -c database.yml --apply
```

### 3
Add an option for `renamed_from`.
```
create_table :art_categories, force: :cascade, renamed_from: :arts do |t|
# *-* columns *-*
end
```

### End
It will be outputting an error message.

### `--dry-run` is true
```
Please run 'bundle exec rake apply:env DRY_RUN=false' if you want to apply.
Apply `Schemafile` (dry-run)
rename_table(:arts, "art_categories")

drop_table("arts")

# RENAME TABLE `arts` TO `art_categories`
# DROP TABLE `arts`
```

### `--dry-run is false`
```
Apply `Schemafile`
-- rename_table(:arts, "art_categories")
   -> 0.0069s
-- drop_table("arts")
[ERROR] Mysql2::Error: Unknown table 'project_test.arts': DROP TABLE `arts`
  1: rename_table(:arts, "art_categories")
  2:
* 3: drop_table("arts")
```

**Comment by winebarrel** [comment]
Thank you for your report!

**Comment by winebarrel** [comment]
v0.6.6.beta3 has been released.
I think that was probably fixed.
Thanks! :-)

**Comment by sachin21** [comment]
@winebarrel Wonderful! Thank you so much!
