### ISSUE TITLE
migration fail when `rename_from` is written in Schemafile

### ISSUE THREAD

**Issue by nasum** [winebarrel/ridgepole#144]
Hi there.  Thank you for creating powerfule gem. It is very helpful.
I have one question. 

First executing `db: create` on CircleCI, next running `ridgepole apply`. Then migration failed.I think, that it is an error because the rename target does not exist.

Is this behavior specification? If so, how should we solve this problem?

**Comment by winebarrel** [comment]
Thank you for uging ridgepole :-)

> Is this behavior specification? If so, how should we solve this problem?

You may be misspelling a keyword.
`s/rename_from/renamed_from/`

**Comment by nasum** [comment]
I'm sorry, I mistyped.
I have simple test.
https://github.com/nasum/test_ridgepole/blob/master/Schemafile#L3
This is the log when we executed this project.

create database.
```bash
[masaya]$ bundle exec rails db:create
Created database 'test_ridgepole_development'
Created database 'test_ridgepole_test'
```

apply schemafile
```bash
[masaya]$ bundle exec ridgepole -c config/database.yml -a
Apply `Schemafile`
-- rename_table("tests", "rename_tests")
[ERROR] Mysql2::Error: Table 'test_ridgepole_development.tests' doesn't exist: RENAME TABLE `tests` TO `rename_tests`
* 1: rename_table("tests", "rename_tests")
        /Users/masaya/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
```
