### ISSUE TITLE
Unknown type 'geometry' for column 'latlng'

### ISSUE THREAD

**Issue by YuK1Game** [winebarrel/ridgepole#253]
Hi

I dumped the DB.
However, the following error occurred.

`ridgepole -c database.yml -E development --export --output schema/Schemafile`

results

```
[WARNING] Could not dump table "location" because of following StandardError
   Unknown type 'geometry' for column 'latlng'
```

Is this tool not compatible with the geometry type?
Or is there no plan to respond?

versions
```
$ ridgepole -v
ridgepole 0.7.4
```

Thanks.

**Comment by winebarrel** [comment]
ridgepole is dependent on the ActiveRecoed, but ActiveRecoed does not support the geometry type.
If you want to use geometry type, please refer to the following URL:

- https://so-wh.at/entry/2017/08/11/134530
- http://poketo7878-dev.hatenablog.com/entry/2017/10/25/191447
