### ISSUE TITLE
Creating a string Primary Key called "id"

### ISSUE THREAD

**Issue by CamilleDrapier** [winebarrel/ridgepole#262]
Hi,

This is a bit out of the road, as in a simpler fashion, I should just accept to have a regular id and a functional separate column with a unique index, but in the end I had to try to do this with a string id column...
So, I was trying to create a primary key of a table as this (from an empty database each time):

```
create_table "tests", primary_key: :id do |t|
 t.string :id, null: false
end
```

which gave me this:

```
Apply `Schemafile`
-- create_table("tests", {:primary_key=>"id"})
[ERROR] you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to create_table.
  1: create_table("tests", {:primary_key=>"id"}) do |t|
* 2:   t.column("id", :"string", {:null=>false})
  3:   end
	/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:361:in `column'
```

Then, if I define my schema as follows:

```
create_table "tests", id: false, primary_key: :id do |t|
 t.string :id, null: false
end
```

I have this output (no PK!):
```
CREATE TABLE tests (
    id character varying NOT NULL
);
```

After looking a bit around in the code and trying various things, if I defined this:
```
create_table "tests", primary_key: [:id] do |t|
 t.string :id, null: false
end
```

Which finally gave me this:
```
CREATE TABLE tests (
    id character varying PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tests_pkey ON tests(id text_ops);
```

I have the feeling that this is currently only possible because of the added support on multiple columns PKs. Is that right ? Would it be possible to support this in a different way ? Also the initial message error tells us to set the `:id` option to false but that ends up in not defining a primary key even if specified... (maybe there should be a warning in that case?) 

Thanks in advance!

**Comment by winebarrel** [comment]
Thanks for the report :smiley: 

If you are using PostgreSQL and Rails 5.2, you may be able to solve the problem with the following DSL:

```ruby
create_table "tests", id: :string do |t|
end
```

This DSL will be converted to the following SQL:

```sql
CREATE TABLE "tests" ("id" character varying NOT NULL PRIMARY KEY)
```

**Comment by CamilleDrapier** [comment]
Nice! This works fine! Sorry for not trying that earlier. 😃
