### ISSUE TITLE
`:Ignore` option ignores the column definition when CREATE TABLE

### ISSUE THREAD

**Issue by gecko655** [winebarrel/ridgepole#271]
I want to make sure the functionality of the option `:ignore`.

Suppose I have an empty (no tables) DB and I apply the Schemafile below.

```ruby
create_table "test", force: :cascade do |t|
  t.integer "test_ignore", ignore: true
  t.integer "test_not_ignore"
end
```

I expected the `:ignore` option is effective AFTER the table is already created and not effective when creating the table.
In this case, I thought the table should have a column `test_ignore` and the schema would be like:

```
mysql> desc test;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| test_ignore     | int(11)      | YES  |     | NULL    |                |
| test_not_ignore | int(11)      | YES  |     | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
```

But, the table actually was like:

```
mysql> desc test;
+-----------------+------------+------+-----+---------+----------------+
| Field           | Type       | Null | Key | Default | Extra          |
+-----------------+------------+------+-----+---------+----------------+
| id              | bigint(20) | NO   | PRI | NULL    | auto_increment |
| test_not_ignore | int(11)    | YES  |     | NULL    |                |
+-----------------+------------+------+-----+---------+----------------+
```

Is this an intended behavior?

With this behavior, we should create the table first without `:ignore` option, and then add the option to prevent changes to the column.
In my case, I know some columns will have to ignore changes in advance.
So declaring an `:ignore` column and creating the table WITH the column is more comfortable behavior for me.

I tested with ridgepole 0.7.6 & MySQL 8.0.15, PostgreSQL 11.2.

**Comment by winebarrel** [comment]
> Is this an intended behavior?

Yes.

If you use `:ignore`, you need to use `#execute` to create columns:

(e.g. MySQL)
```ruby
create_table "test", force: :cascade do |t|
  t.integer "test_ignore", ignore: true
  t.integer "test_not_ignore"
end

execute("ALTER TABLE test ADD COLUMN test_ignore INT") do |c|
  # Execute SQL only if there is no column
  c.raw_connection.query(<<-SQL).each.length.zero?
    SELECT 1 FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = 'xxx'
      AND TABLE_NAME = 'test'
      AND COLUMN_NAME = 'test_ignore'
  SQL
end
```

> In my case, I know some columns will have to ignore changes in advance.

Could you tell me more about your use case?
(Why not prohibit changes after creating a column)

It may be better to add `--ignore-without-create` option.

**Comment by gecko655** [comment]
After my further investigation, the root cause of my case was the fault of https://github.com/ValiMail/postshift .
In postshift, Ruby's `time` is bound to RedShift's `timestamptz`, but after creating `timestamptz` column, ridgepole claims a change to the column continuously.
I wanted to suppress the change to such `timestamptz` column.

But, it's not a ridgepole issue and I probably found how the postshift repository should be bug-fixed.
So, I'd like to close this issue.
Thank you for reviewing my issue. :pray:

---

By the way, my first thought was, declaring `ignore: true` is equivalent to ruby DSL's comment out.

The following ridgepole DSL
```ruby
t.integer "test_ignore", ignore: true
```
is, as far as I know, equivalent to the following.
```ruby
# t.integer "test_ignore"
```

I wondered why `ignore:` is implemented.

**Comment by winebarrel** [comment]
> By the way, my first thought was, declaring ignore: true is equivalent to ruby DSL's comment out.
> I wondered why ignore: is implemented.

It is because to allow users to add columns that are not supported by Rails.
Ignored column are not created but **not deleted**.
(Columns commented out are deleted.)

**Comment by gecko655** [comment]
Oh, that's true... I missed that situation.
Thank you for letting me know!
