### ISSUE TITLE
Using "using: :hash" in add_index generate remove_index and add_index everytime

### ISSUE THREAD

**Issue by S-YOU** [winebarrel/ridgepole#294]
```
Apply `db/Schemafile`
-- remove_index("table_name", {:name=>"column_name_index"})
   -> 0.0129s
-- add_index("table_name", ["column_name"], {:name=>"column_name_index", :using=>:hash, :unique=>false})
   -> 0.0178s
```

**Comment by winebarrel** [comment]
Please write the version of MySQL and ridgepole you are using.

---

InnoDB does not support Hash indexes in MySQL 5.6 / 5.7.
Hash index can be selected only by Memory engine.

**Comment by S-YOU** [comment]
> InnoDB does not support Hash indexes in MySQL 5.6 / 5.7.

Ah, that's why I didn't know that. It was MySQL 5.7, but when I do show create table, I see that 
```
KEY `column_name_index ` (`column_name`) USING HASH
```
Isn't that hash algorithm is applying?

**Comment by S-YOU** [comment]
Figured that hash algorithm is really aren't applying when I do show indexes. Thank you.
