### ISSUE TITLE
How to create foregn_key with different to_table_name and column_name

### ISSUE THREAD

**Issue by hikaruna** [winebarrel/ridgepole#300]
If the feature doesn't exist, request the feature

**Comment by winebarrel** [comment]
Can you give us some specific examples?

**Comment by hikaruna** [comment]
@winebarrel 

https://ja.stackoverflow.com/questions/67467/ridgepole%e3%81%a7foreign-key%e3%82%92to-table%e3%81%a8%e5%88%a5%e5%90%8d%e3%81%aecolumn-name%e3%81%a7%e7%94%9f%e6%88%90%e3%81%99%e3%82%8b%e6%96%b9%e6%b3%95/67491#67491

please add document.

**Comment by winebarrel** [comment]
Thank you for your report. 😃 
The syntax of ridgepole basically follows the Rails migration.
Please refer to the Rails documentation.

**Comment by hikaruna** [comment]
@winebarrel OK thanks.

But, This tool has many differences from the rails migration api. ex: ( https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Table.html#method-i-foreign_key ), and Readme shows it can be used without rails.

So

> The syntax of ridgepole basically follows the Rails migration.
Please refer to the Rails documentation.

This is not obvious.
After all, I thought it would be more user friendly to add text to the Readme.
