### ISSUE TITLE
Add option to throw error on adding foreign key without index

### ISSUE THREAD

**Issue by kyontan** [winebarrel/ridgepole#302]
Hello,

I have met the problem about foreign key with no index, and proposes changing behaviour about it.

In #290, in the case of MySQL (InnoDB), trying to add_foreign_key without index displays warning.
I think the warning is not enough and throwing error is more better because it's not idempotent.

(I met the problem in my system that executes `ridgepole apply`multiple times in a time (I know it's strange), and found error in its second execution, I couldn't found its mistake in CI)

Also, I have confused about its error message `please add an index explicitly for your future operations`.
I thought its `future operation` is far from now, but it is just next `ridgepole apply`.
I agree that the future includes `next time`, but I suspect wording like `please add an index before your next operation` or like it is preferable.

**Comment by abicky** [comment]
> I agree that the future includes `next time`, but I suspect wording like `please add an index before your next operation` or like it is preferable.

I've changed the warning message in https://github.com/winebarrel/ridgepole/pull/307.

By the way, I think always raising an error is better than adding an option.
@winebarrel What do you think about that? If you agree with me, I'll change the behavior.

**Comment by winebarrel** [comment]
Since it is a specification only for MySQL, I think it is not good to always raise an error.
How about raising an error only for MySQL?

**Comment by winebarrel** [comment]
> How about raising an error only for MySQL?

`check_foreign_key_without_index` was already a MySQL-only check...

> By the way, I think always raising an error is better than adding an option.

I agree with your idea 👍

**Comment by abicky** [comment]
> I agree with your idea 👍

Thank you for your reply! I created the pull request https://github.com/winebarrel/ridgepole/pull/310.

**Comment by abicky** [comment]
I released the new version 0.8.10, which raises an error if an InnoDB column has a foreign key but no index, so I'll close this issue.
