### ISSUE TITLE
Inconsistent AUTO_INCREMENT not in CREATE TABLE but added to ALTER

### ISSUE THREAD

**Issue by atnak** [winebarrel/ridgepole#320]
Tested version: 0.8.2

# Summary

Handling of `AUTO_INCREMENT` is inconsistent between CREATE TABLE and ALTER.

# Reproducing

1. First create a table:

    ```sh
    ridgepole --apply --config ... \
      --skip-drop-table --mysql-use-alter --allow-pk-change --debug \
     --file <(echo 'create_table "foo", id: :integer, unsigned: true, default: nil do end')
    ```

* The above command creates a table without `AUTO_INCREMENT`: 

    ```
    -- create_table("foo", {:id=>:integer, :unsigned=>true, :default=>nil})
       (3.0ms)  CREATE TABLE `foo` (`id` int unsigned NOT NULL PRIMARY KEY)
       -> 0.0044s
    ```

2. Next switch the signedness of the primary key by changing to `unsigned: false`:

    ```sh
    ridgepole --apply --config ... \
      --skip-drop-table --mysql-use-alter --allow-pk-change --debug \
     --file <(echo 'create_table "foo", id: :integer, unsigned: false, default: nil do end')
    ```

* The ALTER gets `AUTO_INCREMENT` for some reason:

    ```
    -- change_column("foo", :id, :integer, {:unsigned=>false, :auto_increment=>true, :comment=>nil})
       (8.7ms)  ALTER TABLE `foo` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT
       -> 0.0102s
    ```

3. Drop the example table and reverse the steps above performing 2 first then 1.  ALTER will still get `AUTO_INCREMENT` and CREATE TABLE will not.

# Expected

ALTER to not have `AUTO_INCREMENT` to make it consistent with CREATE TABLE, and because `default: nil` is set which CREATE TABLE seems to be using as the indicator for not applying `AUTO_INCREMENT`.

**Comment by winebarrel** [comment]
fixed https://github.com/winebarrel/ridgepole/pull/334
