### ISSUE TITLE
--alter-extra option cannot work on unique index

### ISSUE THREAD

**Issue by eguchi-ken** [winebarrel/ridgepole#355]
--alter-extra option works on normal index, but it's not work on unique index.

https://github.com/winebarrel/ridgepole/blob/1847a679dfbcd10ca6572a56afab22a8724dc897/lib/ridgepole/execute_expander.rb#L48-L62

I think it could be improved by modifying line 53 as follows.

```diff
-       when /\A(CREATE|DROP)\s+INDEX\b/i 
+       when /\A(CREATE|DROP)\s+(UNIQUE\s+)?INDEX\b/i 
```

Can you please fix it?

**Comment by winebarrel** [comment]
Thank you for reporting. Fixed in # 356

**Comment by winebarrel** [comment]
v0.9.4 has been released
