### ISSUE TITLE
ridgepole 0.5.2 fails to identify tables when having a dry run

### ISSUE THREAD

**Issue by plonk** [winebarrel/ridgepole#37]
It looks for a table with a lowercase 'a' put in front and reports an error in some cases like changing a field type. 

    $ ls
    Schemafile  config.yml
    $ cat config.yml
    adapter: sqlite3
    encoding: utf8
    database: test.db
    $ cat Schemafile 
    create_table "users", force: true do |t|
      t.string  "name"
    end
    $ ridgepole -c config.yml --apply 
    Apply `Schemafile`
    -- create_table("users", {})
    $ sed 's/string/integer/' < Schemafile > tmp
    $ mv tmp Schemafile
    $ cat Schemafile 
    create_table "users", force: true do |t|
      t.integer  "name"
    end
    $ ridgepole -c config.yml --apply --dry-run
    Apply `Schemafile` (dry-run)
    change_column("users", "name", :integer, {:null=>true, :default=>nil})
    
    [ERROR] Could not find table 'ausers'
    * 1: change_column("users", "name", :integer, {:null=>true, :default=>nil})

The actual migration works fine. 

    $ ridgepole -c config.yml --apply 
    Apply `Schemafile`
    -- change_column("users", "name", :integer, {:null=>true, :default=>nil})
       -> 0.0499s

Ruby version: 2.1.2p95 on Linux.

**Comment by winebarrel** [comment]
Thanks! :smiley: 
I will fix it next week, please wait a little :pray:

**Comment by winebarrel** [comment]
@plonk Fix sqlite3 dry-run bug, and release [0.5.3.beta](https://rubygems.org/gems/ridgepole/versions/0.5.3.beta) :smiley: 

But the internal process of sqlite3 adapter is too special, so there may be still a problem...
