### ISSUE TITLE
psgl uuid suport?

### ISSUE THREAD

**Issue by yss44** [winebarrel/ridgepole#42]
postgres uuid table definition not work. example 
```ruby
create_table :books do |t|
  t.uuid :uuid
end
```
 [here](https://github.com/yss44/ridgepole/commit/776c7a69c016539877de51fd431ec59ee90c1ea4) is my temporary patch.

**Comment by winebarrel** [comment]
Thanks! :smiley:

**Comment by winebarrel** [comment]
Thanks! :smiley: 
I will fix.

**Comment by yss44** [comment]
:+1:

**Comment by winebarrel** [comment]
[v0.6.1.beta](https://rubygems.org/gems/ridgepole/versions/0.6.1.beta) has been released.

Please try it out! :smiley:

**Comment by yss44** [comment]
great! I will try it soon!
