### ISSUE TITLE
複合インデックスに含まれる列の列名変更でエラー

### ISSUE THREAD

**Issue by arithkatsumata** [winebarrel/ridgepole#43]
hogeというテーブルの「type」列の列名を「ranking_type」に変更してridgepoleをdry-runで実行してみたところ、下記のように出力されました。(add_indexの部分で、正しくは「ranking_type」と「target_id」の2列の複合インデックスになる必要があるが、古い「type」という列名が使用されてしまっている)

「複合インデックスに含まれる列の列名を変更」した場合に、そのインデックスを再作成する部分のロジックに誤りがあるのではないかと思われます。

add_column("hoge", "ranking_type", :integer, {:limit=>4, :null=>false, :first=>true})
remove_column("hoge", "type")
remove_index("hoge", {:name=>"uq_hoge_01"})
add_index("hoge", ["type", "target_id"], {:name=>"uq_hoge_01", :unique=>true, :using=>:btree})

**Comment by winebarrel** [comment]
DBの種類を教えていただけますか？

**Comment by arithkatsumata** [comment]
DB:MySQL 5.6
Ruby 2.2
Rails 4.2.1
Ridgepole 0.6.0
になります。

**Comment by winebarrel** [comment]
情報ありがとうございます！

**Comment by arithkatsumata** [comment]
あ〜申し訳ありませんこちら私の勘違いでした！(汗)

インデックスに含まれる列名を変更する場合は、当たり前ですが.schemaファイルのadd_indexの行も変更しないとダメですよね〜すみません・・・。

remove indexが自動的に行われていたので、add indexの部分も自動的に修正が入るものだと勝手に思い込んでおりました。失礼いたしましたcloseさせて頂きますm(__)m

**Comment by winebarrel** [comment]
了解です！
