### ISSUE TITLE
options: "ENGINE=InnoDB DEFAULT CHARSET=utf8"がexportに適用されない

### ISSUE THREAD

**Issue by lastcat** [winebarrel/ridgepole#47]
タイトルの通りです。
 ` options: "ENGINE=InnoDB DEFAULT CHARSET=utf8`のdiffでapply時に毎回[WARNING]が出るようになってしまったので、一度exportしようと思ったのですが、このoptionの部分がexportされた.schemaファイルに適用されていないようです(本来 `--table-options`オプションで解決するべき問題なのかもしれませんが、このoptionのsyntaxがよくわからなかったので……)。

## 環境
 - rails (4.2.1)
 - ridgepole (0.6.2)
 - activerecord-mysql-awesome (0.0.4)
 - database.yml
```
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
```
- 実行コマンド
(Schemafileは各.schemaファイルをrequireしている構造です)

```
 @apply
ridgepole --apply --file my_railsapp_proj/db/ridgepole/Schemafile --enable-mysql-awesome

 @export
ridgepole --export --output  my_railsapp_proj/db/ridgepole//Schemafile --split
```

 - .schemaファイルの一行目
```
create_table "<model names>", force: :cascade do |t|
```
 - apply時の出力
```
[WARNING] Table `<model names>` options cannot be changed
```
- lib/ridgepole/diff.rb内のscan_changeメソッド内で`from`を出力した結果(抜粋)

```
@from
definition: ~省略~
options:
{:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8"}
indeces: ~省略~
```

この状況でexportを実行しても.schemaファイルの一行目に変化はありませんでした。

**Comment by winebarrel** [comment]
Issueありがとうございます。
export時に --enable-mysql-awesome オプションを付けることで解決しないでしょうか？

**Comment by lastcat** [comment]
すいません、それで解決しました……ありがとうございました。

**Comment by winebarrel** [comment]
了解です！
