### ISSUE TITLE
Workaround for schema changes with data migration?

### ISSUE THREAD

**Issue by hayamiz** [winebarrel/ridgepole#53]
Is there any workaround for schema changes with data migration, like table splitting, column name change, etc?

For example, consider this story:
* Suppose a blog-like app. At first, each entry has only one image file.
* At some point, I want to change the schema so that each entry has multiple image files.

`Schemafile`s will be like this.
before:
~~~
create_table "entries" do |t|
  t.string  "title"
  t.string  "imgfile_path"
end
~~~

after:
~~~
create_table "entries" do |t|
  t.string  "title"
end

create_table "imgfiles" do |t|
  t.string "path"
  t.integer  "entry_id"
end
~~~

In this case, simply running ridgepole with "after" version Schemafile would just delete `imgfile_path` attribute from `entries` table, and create empty "imgfiles" table.

One possible procedure for correct schema change is:
1. create "imgfiles" table by ridgepole
2. copy "entries.imgfile_path" data to "imgfiles" table by some script
3. delete "imgfile_path" attribute from "entries" by ridgepole

However this procedure is error-prone manual steps.
It would be great if anyone could share good practice for this kind of problems.

Anyway thanks for good product :smiley:

**Comment by winebarrel** [comment]
I'm sorry reply late.

ridgepole supports `execute` methods.
So you can perform data migration as follows:

```ruby
execute("INSERT INTO imgfiles (path, entry_id) SELECT imgfile_path, id FROM entries") do |c|
  c.raw_connection.query("SELECT COUNT(*) FROM imgfiles").each.length.zero?
end
```

But I think that it is not a good solution.

I think it is better to manage the data migration using other tool. e.g. [liquibase](http://www.liquibase.org/), [flyway](http://flywaydb.org/)
(I recommend **liquibase**)

Procedure of data migration is as follows:

1. create "imgfiles" table by ridgepole
1. migrate data from "entries" to "imgfiles" by liquibase/flyway
1. delete "imgfile_path" attribute from "entries" by ridgepole

Do your problem will solve?

**Comment by winebarrel** [comment]
Will close the issue.
@hayamiz Please reopen Issue if your problem is not resolved.
