### ISSUE TITLE
Can ridgepole treat sql view?

### ISSUE THREAD

**Issue by kiemie** [winebarrel/ridgepole#54]
Is there any solution to treat SQL view with ridgepole?

I tried to create view by using execute method in schema file like as below, but something went wrong.

``` ruby
# examples.schema
execute( <<-SQL
CREATE VIEW examples AS
SELECT column1, column2
FROM 'some_table
SQL
)
```

``` ruby
# Schemafile
require 'some_table.schema'
... (snip) ...
require 'examples.schema'
```

Then Apply schema like as below

``` ruby
ridgepole -c config.yml --apply
```

It worked fine. SQL view was created.
But then I re-execute ridgepole, I could see error message as below

``` shell
Mysql2::Error: Unknown table 'dbname.examples': DROP TABLE `examples`
```

I guess it because of running drop_table('examples') although 'examples' is NOT table but view.
Could you tell me how should I treat SQL view in ridgepole?

My environments are

- ridgepole: 0.6.2
- mysql2(gem): 0.3.19
- ruby: 2.1.6p336

**Comment by winebarrel** [comment]
I'm sorry. It is not possible to support the view...

**Comment by a-suenami** [comment]
@winebarrel Can I submit a pull request about `create_view` ? Or should I make other gem?

**Comment by winebarrel** [comment]
@a-suenami Thank you for proposal 😃 

I do not want to extend the Rails in ridgepole.
If you make a generic `create_view` gem, will support it.

**Comment by a-suenami** [comment]
ok, thanks for your reply 😄 
i think about making gem to support view.
