### ISSUE TITLE
WARNING message don't look apposite for no-diff logging.

### ISSUE THREAD

**Issue by timakin** [winebarrel/ridgepole#59]
[WARNING message](https://github.com/winebarrel/ridgepole/blob/6323f2e2a90708e05f8709b1c31df996262733b3/lib/ridgepole/diff.rb#L91) for scanning difference between "from" and "to" of DB schema don't look good for the purpose.
`[WARNING] Table `***` options cannot be changed` shows it's "unable" to change schema.
But in this case, this module should show "there is no difference".
So it should be like `[INFO] No difference of configured options in table {table_name} from previous migration.`

**Comment by winebarrel** [comment]
well..

If ridgepole user tried to change the table options but the table option was not changed,
I think it should be warning.

If the warning is noisy, I think it is better to add following option: `--ignore-table-options-warning`

What do you think?

**Comment by timakin** [comment]
@winebarrel 
thx for your reply.
> If ridgepole user tried to change the table options but the table option was not changed,
I think it should be warning.
I'm sure that the log level should be `warning`, but `cannot be changed` is too strong description.
I'd like to get the message `[WARNING] No difference of schema configuration for table {table_name}. (if you changed some options, please reconfirm your Schemafile.) ` may be better for this case.

**Comment by winebarrel** [comment]
I understand.
Will fix the message.
