### ISSUE TITLE
Add text/blob option for mysql (implemented in Rails 5)

### ISSUE THREAD

**Issue by timakin** [winebarrel/ridgepole#82]
Dear, @winebarrel .

I'd like to set text/blob type of following on Schemafile.

https://github.com/rails/rails/commit/059820c09afaf18e2d29da61db0e0a3215989b89

Can I add them to dsl_parser.rb and create pull-req?
https://github.com/winebarrel/ridgepole/blob/v0.6.5/lib/ridgepole/dsl_parser.rb#L21

**Comment by winebarrel** [comment]
Thanks for your report!
This issue is fixed. 😃
