### ISSUE TITLE
Diff always appears with charset

### ISSUE THREAD

**Issue by sonots** [winebarrel/ridgepole#87]
Versions:

* ruby 2.3.0p0
* Using activerecord 4.2.4
* Using activerecord-mysql-awesome 0.0.8
* Using ridgepole 0.6.

With DSL like,

```
  t.string   "cc_address", limit: 64, charset: 'latin1', null: false
```

and ridpole command,

```
ridgepole --debug --file Schemafile -c config/databas
e.yml --enable-mysql-awesome --ignore-table repli_chk,repli_clock --apply -E development
```

Ridgepole always give me a diff as

```
-- change_column("himportdb_importjob", "cc_address", :string, {:limit=>64, :charset=>"latin1", :null=>false, :default=>nil, :unsigned=>false})
   (25.5ms)  ALTER TABLE `himportdb_importjob` CHANGE `cc_address` `cc_address` varchar(64) CHARACTER SET latin1 NOT NULL
   -> 0.0400s
```

**Comment by sonots** [comment]
Looking values at Ridgepole::Client#diff,

current_definition:

```
cc_address"=>{:type=>:string, :options=>{:limit=>64, :null=>false, :collation=>"latin1_swedish_ci"}}
```

expected_definition:

```
"cc_address"=>{:type=>:string, :options=>{:limit=>64, :charset=>"latin1", :null=>false}}
```

**Comment by kamipo** [comment]
activerecord 5.0.0 and activerecord-mysql-awesome are dumping a collation rather than charset because it does not determine whether the default collation for charset.
To specify as a collation may solve the issue if it is possible.

**Comment by sonots** [comment]
Thanks! Diff was resolved. I will send PR to note about it on README.

**Comment by winebarrel** [comment]
@kamipo Thank you for answering 🙇
