### ISSUE TITLE
Ridgepole cannot handle bigint columns

### ISSUE THREAD

**Issue by aamine** [winebarrel/ridgepole#90]
It seems ridgepole cannot detect bigint column attributes (?) and repeatedly generate ALTER statement.

Example schema file (bigint_test.schema)
```
create_table 'bigint_test', id: false do |t|
  t.bigint 'b'
end
```

Apply #1 
```
% be ridgepole -c ../config/database.yml -E production -f bigint_test.schema --apply
Apply `bigint_test.schema`
-- create_table("bigint_test", {:id=>false})
   -> 0.0027s
```
This is OK.

Apply #2 
```
% be ridgepole -c ../config/database.yml -E production -f bigint_test.schema --apply
Apply `bigint_test.schema`
-- change_column("bigint_test", "b", :bigint, {:null=>true, :default=>nil})
   -> 0.0026s
```
Why ALTER ???

Apply #3 
```
% be ridgepole -c ../config/database.yml -E production -f bigint_test.schema --apply
Apply `bigint_test.schema`
-- change_column("bigint_test", "b", :bigint, {:null=>true, :default=>nil})
   -> 0.0025s
```
It repeatedly generates ALTER statement and never converge.

### Environment

- PostgreSQL 9.5.0
- Ruby 2.3.1p112
- Ridgepole 0.6.4 and master HEAD
- pg 0.18.4
- Mac OS X 10.11.5 (El Capitan)

**Comment by winebarrel** [comment]
Thanks for your report 😃 

Please try the following DSL if you're using the Rails 4.x.

```ruby
          create_table "bigint_test", id: false, force: :cascade do |t|
            t.integer "b", limit: 8
          end
```

**Comment by aamine** [comment]
!!  Thanks, It magically works!
For future reference... exporting schema from database is preferred rather than writing schema file by hand?

**Comment by winebarrel** [comment]
> exporting schema from database is preferred rather than writing schema file by hand?

I think that there is no problem to write by hand.
However, you will need to write DSL that is the same as  the exported DSL.

**Comment by aamine** [comment]
OK, I get it.  Thanks!!
