### ISSUE TITLE
Unexpected behavior in applying multiple times with `add_foreign_key`.

### ISSUE THREAD

**Issue by hshimoyama** [winebarrel/ridgepole#96]
I applied this Schemafile twice.

```rb
create_table :hoges do |t|
end

create_table :fugas do |t|
  t.integer :hoge_id
end
add_foreign_key :fugas, :hoges, name: "fk_fugas_hoges"
# If `add_index` for this `add_foreign_key' is added, this error is suppressed.
# add_index :fugas, :hoge_id, name: "fk_fugas_hoges"
```

And ridgepole returned an error described below.

```
-- remove_index("fugas", {:name=>"fk_fugas_hoges"})
[ERROR] Mysql2::Error: Cannot drop index 'fk_fugas_hoges': needed in a foreign key constraint: DROP INDEX `fk_fugas_hoges` ON `fugas`
* 1: remove_index("fugas", {:name=>"fk_fugas_hoges"})
```

Index named `fk_fugas_hoges' is created and needed by foreign key constraint but ridgepole detects this index as unused index and try to remove it.
I think this behavior is unexpected.

ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
MySQL: mysql  Ver 14.14 Distrib 5.7.15, for osx10.11 (x86_64) using  EditLine wrapper
ridgepole: ridgepole (0.6.4) and ridgepole (0.6.5beta12)

**Comment by winebarrel** [comment]
In MySQL, `ADD CONSTRAINT` is generate index automatically.

> For ALTER TABLE, unlike CREATE TABLE, ADD FOREIGN KEY ignores index_name if given and uses an automatically generated foreign key name. As a workaround, include the CONSTRAINT clause to specify the foreign key name:
http://dev.mysql.com/doc/refman/5.6/en/alter-table.html

Please define explicitly index in Schemafile.
I'm sorry.

**Comment by hshimoyama** [comment]
I respect your decision. I'll define explicitly indexes.
Thank you.
