### ISSUE TITLE
[bug] `decimal typed column` is always adopted as `change_column`

### ISSUE THREAD

**Issue by timakin** [winebarrel/ridgepole#99]
Columns typed `decimal` are shown in logs as `changed_column`.
After first time insertion, it endlessly tells that is `changed`.
Is this a bug?

```
create_table 'foo' ...    
    ...
    t.decimal 'latitude', precision: 9, scale: 6, default: 0.0, null: false
    t.decimal 'longitude', precision: 9, scale: 6, default: 0.0, null: false
    ...
end
```

```
-- change_column("foo", "latitude", :decimal, {:precision=>9, :scale=>6, :default=>0.0})
   -> 0.0325s
-- change_column("foo", "longitude", :decimal, {:precision=>9, :scale=>6, :default=>0.0})
   -> 0.0183s
```

**Comment by kamipo** [comment]
How about change `default: 0.0` to `default: "0.0"`?

**Comment by timakin** [comment]
Fixed, and thanks for a quick response.
But is this the expected setting?
Cause' of `.`, should it braced with double quotation?

**Comment by kamipo** [comment]
Ridgepole compares `Schemafile` and dumped DSL by `ActiveRecord::SchemaDumper`.
The default value of decimal (with scale) type is dumped as a string.
Therefore the default value in `Schemafile` should be a string.

**Comment by timakin** [comment]
Thanks, and now I found it on `ActiveRecord::SchemaDumper`.
But if the default value type was wrong,
should `SchemaDumper` return alerts on log?

**Comment by kamipo** [comment]
I don't know what the case your mentioned (the default value type was wrong in `SchemaDumper`).
`SchemaDumper` extracts schema information from existing database (schema),
therefore all default values are valid.

**Comment by timakin** [comment]
Sorry, I misunderstood about that.
I'm so appreciate you answering so many times.

Finally, I just have a question where should this case be handled.
Until now, I couldn't know `default type was invalid` from ridgepole log.
(Because it shows just it was `change_column`.)

**Comment by winebarrel** [comment]
@timakin Sorry for the late reply 🙇 
@kamipo Thank you for your comment!!

> Until now, I couldn't know default type was invalid from ridgepole log.

Please use `--verbose` option.
It show column definition mismatch in console.

```
$ ridgepole -c '{adapter: mysql2, database: test}' -a --verbose
Apply `Schemafile`
# Parse DSL
# Load tables
#   foo
# Compare definitions
#   foo
 {:definition=>
   {"latitude"=>
     {:type=>:decimal,
-     :options=>{:precision=>9, :scale=>6, :default=>"0.0", :null=>false}},
+     :options=>{:precision=>9, :scale=>6, :default=>0.0, :null=>false}},
    "longitude"=>
     {:type=>:decimal,
-     :options=>{:precision=>9, :scale=>6, :default=>"0.0", :null=>false}}},
+     :options=>{:precision=>9, :scale=>6, :default=>0.0, :null=>false}}},
  :options=>{:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8"}}
# Update schema
-- change_column("foo", "latitude", :decimal, {:precision=>9, :scale=>6, :default=>0.0})
   -> 0.0382s
-- change_column("foo", "longitude", :decimal, {:precision=>9, :scale=>6, :default=>0.0})
   -> 0.0155s
```
